### ISSUE TITLE
no config file “lineageos_nx569j_defconfig” ,which file should I use in BoardConfig.mk ?

### ISSUE THREAD

**Issue by End4You** [HighwayStar/android_kernel_nubia_msm8976#1]
I want to build lineage rom and port for another qcom653 device

**Comment by HighwayStar** [comment]
Check  cm-14.1 and lineage 15.1 branches 

https://github.com/HighwayStar/android_kernel_nubia_msm8976/blob/staging/cm-14.1/arch/arm64/configs/lineageos_nx569j_defconfig

https://github.com/HighwayStar/android_kernel_nubia_msm8976/blob/staging/lineage-15.1/arch/arm64/configs/lineageos_nx569j_defconfig

**Comment by End4You** [comment]
thanks!
